import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Josefin_Sans, Kalam } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

const josefinSans = Josefin_Sans({ subsets: ['latin'], weight: ['300', '400'] })
const kalamSans = Kalam({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-kalam',
})

export const metadata: Metadata = {
	title: 'Tripper',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cn(josefinSans.className, kalamSans.variable)}>
				{children}
			</body>
		</html>
	)
}
